name: Labels Sync

on:
  push:
    branches: [ main ]
    paths:
      - .github/config/labels.yml
      - .github/workflows/labels-sync.yml
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Sync repository labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/config/labels.yml
          delete-other-labels: true
